server:
  port: 8080

bth:
  ui:
    redis:
      host: localhost
      port: 8090

spring:

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:client}
            client-secret: ${GOOGLE_CLIENT_SECRET:secret}
          github:
            client-id: ${GITHUB_CLIENT_ID:client}
            client-secret: ${GITHUB_CLIENT_SECRET:secret}