server:
  port: 8080

bth:
  ui:
    data-service:
      url: http://localhost:8081/graphql
    redis:
      host: localhost
      port: 6379

spring:

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}